package:
    name: tesserocr
    version: 2.3.1
requirements:
  build:
    - python  
  run:
    - python
about:
    home: https://github.com/sirfz/tesserocr
    license: MIT
    summary: A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using
        Cython
