package:
    name: tesserocr
    version: 2.2.2
about:
    home: https://github.com/sirfz/tesserocr
    license: MIT
    summary: A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using
        Cython
